/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter';
import { OAuthScopePetstoreAuthEnum } from './models/oAuthScopePetstoreAuthEnum';
import { OAuthToken } from './models/oAuthToken';
import { PetstoreAuthManager } from './petstoreAuthManager';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  apiKeyCredentials?: {
    'api_key': string;
  };
  petstoreAuthCredentials?: {
    oAuthClientId: string;
    oAuthRedirectUri: string;
    oAuthToken?: OAuthToken;
    oAuthScopes?: OAuthScopePetstoreAuthEnum[];
    oAuthTokenProvider?: (
      lastOAuthToken: OAuthToken | undefined,
      authManager: PetstoreAuthManager
    ) => Promise<OAuthToken>;
    oAuthOnTokenUpdate?: (token: OAuthToken) => void;
    oAuthClockSkew?: number;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
}
